/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AtualizacaoContato from './model/AtualizacaoContato';
import AtualizacaoElemento from './model/AtualizacaoElemento';
import AtualizacaoExposicao from './model/AtualizacaoExposicao';
import AtualizacaoExposicaoPaineis from './model/AtualizacaoExposicaoPaineis';
import AtualizacaoObra from './model/AtualizacaoObra';
import AtualizacaoPainel from './model/AtualizacaoPainel';
import AtualizacaoUsuario from './model/AtualizacaoUsuario';
import Contato from './model/Contato';
import ConviteExposicao from './model/ConviteExposicao';
import CriacaoUsuario from './model/CriacaoUsuario';
import Elemento from './model/Elemento';
import Exposicao from './model/Exposicao';
import InlineResponse201 from './model/InlineResponse201';
import InlineResponse2011 from './model/InlineResponse2011';
import Notificacao from './model/Notificacao';
import NotificacaoExposicao from './model/NotificacaoExposicao';
import NovaDenuncia from './model/NovaDenuncia';
import NovaExposicao from './model/NovaExposicao';
import NovaNotificacao from './model/NovaNotificacao';
import NovaObra from './model/NovaObra';
import NovoContato from './model/NovoContato';
import NovoPainel from './model/NovoPainel';
import Obra from './model/Obra';
import Painel from './model/Painel';
import Perfil from './model/Perfil';
import ResumoExposicao from './model/ResumoExposicao';
import ResumoMeuPainel from './model/ResumoMeuPainel';
import ResumoPainel from './model/ResumoPainel';
import Usuario from './model/Usuario';
import ExposicaoApi from './api/ExposicaoApi';
import PerfilApi from './api/PerfilApi';
import UsuarioApi from './api/UsuarioApi';

/**
* Definio_OpenAPI_3_0_para_a_API_do_projeto_UnderExpo_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SwaggerUnderExpoOpenApi30 = require('index'); // See note below*.
* var xxxSvc = new SwaggerUnderExpoOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SwaggerUnderExpoOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SwaggerUnderExpoOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SwaggerUnderExpoOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AtualizacaoContato model constructor.
     * @property {module:model/AtualizacaoContato}
     */
    AtualizacaoContato,

    /**
     * The AtualizacaoElemento model constructor.
     * @property {module:model/AtualizacaoElemento}
     */
    AtualizacaoElemento,

    /**
     * The AtualizacaoExposicao model constructor.
     * @property {module:model/AtualizacaoExposicao}
     */
    AtualizacaoExposicao,

    /**
     * The AtualizacaoExposicaoPaineis model constructor.
     * @property {module:model/AtualizacaoExposicaoPaineis}
     */
    AtualizacaoExposicaoPaineis,

    /**
     * The AtualizacaoObra model constructor.
     * @property {module:model/AtualizacaoObra}
     */
    AtualizacaoObra,

    /**
     * The AtualizacaoPainel model constructor.
     * @property {module:model/AtualizacaoPainel}
     */
    AtualizacaoPainel,

    /**
     * The AtualizacaoUsuario model constructor.
     * @property {module:model/AtualizacaoUsuario}
     */
    AtualizacaoUsuario,

    /**
     * The Contato model constructor.
     * @property {module:model/Contato}
     */
    Contato,

    /**
     * The ConviteExposicao model constructor.
     * @property {module:model/ConviteExposicao}
     */
    ConviteExposicao,

    /**
     * The CriacaoUsuario model constructor.
     * @property {module:model/CriacaoUsuario}
     */
    CriacaoUsuario,

    /**
     * The Elemento model constructor.
     * @property {module:model/Elemento}
     */
    Elemento,

    /**
     * The Exposicao model constructor.
     * @property {module:model/Exposicao}
     */
    Exposicao,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse2011 model constructor.
     * @property {module:model/InlineResponse2011}
     */
    InlineResponse2011,

    /**
     * The Notificacao model constructor.
     * @property {module:model/Notificacao}
     */
    Notificacao,

    /**
     * The NotificacaoExposicao model constructor.
     * @property {module:model/NotificacaoExposicao}
     */
    NotificacaoExposicao,

    /**
     * The NovaDenuncia model constructor.
     * @property {module:model/NovaDenuncia}
     */
    NovaDenuncia,

    /**
     * The NovaExposicao model constructor.
     * @property {module:model/NovaExposicao}
     */
    NovaExposicao,

    /**
     * The NovaNotificacao model constructor.
     * @property {module:model/NovaNotificacao}
     */
    NovaNotificacao,

    /**
     * The NovaObra model constructor.
     * @property {module:model/NovaObra}
     */
    NovaObra,

    /**
     * The NovoContato model constructor.
     * @property {module:model/NovoContato}
     */
    NovoContato,

    /**
     * The NovoPainel model constructor.
     * @property {module:model/NovoPainel}
     */
    NovoPainel,

    /**
     * The Obra model constructor.
     * @property {module:model/Obra}
     */
    Obra,

    /**
     * The Painel model constructor.
     * @property {module:model/Painel}
     */
    Painel,

    /**
     * The Perfil model constructor.
     * @property {module:model/Perfil}
     */
    Perfil,

    /**
     * The ResumoExposicao model constructor.
     * @property {module:model/ResumoExposicao}
     */
    ResumoExposicao,

    /**
     * The ResumoMeuPainel model constructor.
     * @property {module:model/ResumoMeuPainel}
     */
    ResumoMeuPainel,

    /**
     * The ResumoPainel model constructor.
     * @property {module:model/ResumoPainel}
     */
    ResumoPainel,

    /**
     * The Usuario model constructor.
     * @property {module:model/Usuario}
     */
    Usuario,

    /**
    * The ExposicaoApi service constructor.
    * @property {module:api/ExposicaoApi}
    */
    ExposicaoApi,

    /**
    * The PerfilApi service constructor.
    * @property {module:api/PerfilApi}
    */
    PerfilApi,

    /**
    * The UsuarioApi service constructor.
    * @property {module:api/UsuarioApi}
    */
    UsuarioApi
};
