/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AtualizacaoUsuario model module.
 * @module model/AtualizacaoUsuario
 * @version 0.0.1
 */
export default class AtualizacaoUsuario {
  /**
   * Constructs a new <code>AtualizacaoUsuario</code>.
   * @alias module:model/AtualizacaoUsuario
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AtualizacaoUsuario</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AtualizacaoUsuario} obj Optional instance to populate.
   * @return {module:model/AtualizacaoUsuario} The populated <code>AtualizacaoUsuario</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AtualizacaoUsuario();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
AtualizacaoUsuario.prototype.nome = undefined;

