/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AtualizacaoExposicaoPaineis model module.
 * @module model/AtualizacaoExposicaoPaineis
 * @version 0.0.1
 */
export class AtualizacaoExposicaoPaineis {
  /**
   * Constructs a new <code>AtualizacaoExposicaoPaineis</code>.
   * @alias module:model/AtualizacaoExposicaoPaineis
   * @class
   * @param id {Number} 
   * @param indice {Number} 
   */
  constructor(id, indice) {
    this.id = id;
    this.indice = indice;
  }

  /**
   * Constructs a <code>AtualizacaoExposicaoPaineis</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AtualizacaoExposicaoPaineis} obj Optional instance to populate.
   * @return {module:model/AtualizacaoExposicaoPaineis} The populated <code>AtualizacaoExposicaoPaineis</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AtualizacaoExposicaoPaineis();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('indice'))
        obj.indice = ApiClient.convertToType(data['indice'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
AtualizacaoExposicaoPaineis.prototype.id = undefined;

/**
 * @member {Number} indice
 */
AtualizacaoExposicaoPaineis.prototype.indice = undefined;

