/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AtualizacaoExposicaoPaineis} from './AtualizacaoExposicaoPaineis';

/**
 * The AtualizacaoExposicao model module.
 * @module model/AtualizacaoExposicao
 * @version 0.0.1
 */
export class AtualizacaoExposicao {
  /**
   * Constructs a new <code>AtualizacaoExposicao</code>.
   * @alias module:model/AtualizacaoExposicao
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AtualizacaoExposicao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AtualizacaoExposicao} obj Optional instance to populate.
   * @return {module:model/AtualizacaoExposicao} The populated <code>AtualizacaoExposicao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AtualizacaoExposicao();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
      if (data.hasOwnProperty('paineis'))
        obj.paineis = ApiClient.convertToType(data['paineis'], [AtualizacaoExposicaoPaineis]);
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
AtualizacaoExposicao.prototype.nome = undefined;

/**
 * @member {String} descricao
 */
AtualizacaoExposicao.prototype.descricao = undefined;

/**
 * @member {Array.<module:model/AtualizacaoExposicaoPaineis>} paineis
 */
AtualizacaoExposicao.prototype.paineis = undefined;

