/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AtualizacaoElemento} from './AtualizacaoElemento';

/**
 * The AtualizacaoPainel model module.
 * @module model/AtualizacaoPainel
 * @version 0.0.1
 */
export class AtualizacaoPainel {
  /**
   * Constructs a new <code>AtualizacaoPainel</code>.
   * @alias module:model/AtualizacaoPainel
   * @class
   * @param nome {String} 
   */
  constructor(nome) {
    this.nome = nome;
  }

  /**
   * Constructs a <code>AtualizacaoPainel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AtualizacaoPainel} obj Optional instance to populate.
   * @return {module:model/AtualizacaoPainel} The populated <code>AtualizacaoPainel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AtualizacaoPainel();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('elementos'))
        obj.elementos = ApiClient.convertToType(data['elementos'], [AtualizacaoElemento]);
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
AtualizacaoPainel.prototype.nome = undefined;

/**
 * @member {Array.<module:model/AtualizacaoElemento>} elementos
 */
AtualizacaoPainel.prototype.elementos = undefined;

