/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Contato model module.
 * @module model/Contato
 * @version 0.0.1
 */
export default class Contato {
  /**
   * Constructs a new <code>Contato</code>.
   * @alias module:model/Contato
   * @class
   * @param id {Number} 
   * @param canal {String} 
   * @param nome {String} 
   * @param link {String} 
   */
  constructor(id, canal, nome, link) {
    this.id = id;
    this.canal = canal;
    this.nome = nome;
    this.link = link;
  }

  /**
   * Constructs a <code>Contato</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Contato} obj Optional instance to populate.
   * @return {module:model/Contato} The populated <code>Contato</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Contato();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('canal'))
        obj.canal = ApiClient.convertToType(data['canal'], 'String');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Contato.prototype.id = undefined;

/**
 * @member {String} canal
 */
Contato.prototype.canal = undefined;

/**
 * @member {String} nome
 */
Contato.prototype.nome = undefined;

/**
 * @member {String} link
 */
Contato.prototype.link = undefined;

