/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CriacaoUsuario model module.
 * @module model/CriacaoUsuario
 * @version 0.0.1
 */
export default class CriacaoUsuario {
  /**
   * Constructs a new <code>CriacaoUsuario</code>.
   * @alias module:model/CriacaoUsuario
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CriacaoUsuario</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CriacaoUsuario} obj Optional instance to populate.
   * @return {module:model/CriacaoUsuario} The populated <code>CriacaoUsuario</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CriacaoUsuario();
      if (data.hasOwnProperty('chave'))
        obj.chave = ApiClient.convertToType(data['chave'], 'String');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} chave
 */
CriacaoUsuario.prototype.chave = undefined;

/**
 * @member {String} nome
 */
CriacaoUsuario.prototype.nome = undefined;

