/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResumoPainel} from './ResumoPainel';

/**
 * The Exposicao model module.
 * @module model/Exposicao
 * @version 0.0.1
 */
export class Exposicao {
  /**
   * Constructs a new <code>Exposicao</code>.
   * @alias module:model/Exposicao
   * @class
   * @param nome {String} 
   * @param organizador {String} 
   */
  constructor(nome, organizador) {
    this.nome = nome;
    this.organizador = organizador;
  }

  /**
   * Constructs a <code>Exposicao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exposicao} obj Optional instance to populate.
   * @return {module:model/Exposicao} The populated <code>Exposicao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Exposicao();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
      if (data.hasOwnProperty('organizador'))
        obj.organizador = ApiClient.convertToType(data['organizador'], 'String');
      if (data.hasOwnProperty('paineis'))
        obj.paineis = ApiClient.convertToType(data['paineis'], [ResumoPainel]);
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
Exposicao.prototype.nome = undefined;

/**
 * @member {String} descricao
 */
Exposicao.prototype.descricao = undefined;

/**
 * @member {String} organizador
 */
Exposicao.prototype.organizador = undefined;

/**
 * @member {Array.<module:model/ResumoPainel>} paineis
 */
Exposicao.prototype.paineis = undefined;

