/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The NotificacaoExposicao model module.
 * @module model/NotificacaoExposicao
 * @version 0.0.1
 */
export default class NotificacaoExposicao {
  /**
   * Constructs a new <code>NotificacaoExposicao</code>.
   * @alias module:model/NotificacaoExposicao
   * @class
   * @param painelId {Number} 
   * @param nome {String} 
   * @param organizador {String} 
   */
  constructor(painelId, nome, organizador) {
    this.painelId = painelId;
    this.nome = nome;
    this.organizador = organizador;
  }

  /**
   * Constructs a <code>NotificacaoExposicao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotificacaoExposicao} obj Optional instance to populate.
   * @return {module:model/NotificacaoExposicao} The populated <code>NotificacaoExposicao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotificacaoExposicao();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('painelId'))
        obj.painelId = ApiClient.convertToType(data['painelId'], 'Number');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('organizador'))
        obj.organizador = ApiClient.convertToType(data['organizador'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
NotificacaoExposicao.prototype.id = undefined;

/**
 * @member {Number} painelId
 */
NotificacaoExposicao.prototype.painelId = undefined;

/**
 * @member {String} nome
 */
NotificacaoExposicao.prototype.nome = undefined;

/**
 * @member {String} organizador
 */
NotificacaoExposicao.prototype.organizador = undefined;

