/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ConviteExposicao} from './ConviteExposicao';

/**
 * The Notificacao model module.
 * @module model/Notificacao
 * @version 0.0.1
 */
export class Notificacao {
  /**
   * Constructs a new <code>Notificacao</code>.
   * @alias module:model/Notificacao
   * @class
   * @param id {Number} 
   * @param expo {module:model/ConviteExposicao} 
   */
  constructor(id, expo) {
    this.id = id;
    this.expo = expo;
  }

  /**
   * Constructs a <code>Notificacao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notificacao} obj Optional instance to populate.
   * @return {module:model/Notificacao} The populated <code>Notificacao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Notificacao();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('expo'))
        obj.expo = ConviteExposicao.constructFromObject(data['expo']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Notificacao.prototype.id = undefined;

/**
 * @member {module:model/ConviteExposicao} expo
 */
Notificacao.prototype.expo = undefined;

