/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NovaExposicao model module.
 * @module model/NovaExposicao
 * @version 0.0.1
 */
export class NovaExposicao {
  /**
   * Constructs a new <code>NovaExposicao</code>.
   * @alias module:model/NovaExposicao
   * @class
   * @param nome {String} 
   * @param descricao {String} 
   */
  constructor(nome, descricao) {
    this.nome = nome;
    this.descricao = descricao;
  }

  /**
   * Constructs a <code>NovaExposicao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NovaExposicao} obj Optional instance to populate.
   * @return {module:model/NovaExposicao} The populated <code>NovaExposicao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NovaExposicao();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
NovaExposicao.prototype.nome = undefined;

/**
 * @member {String} descricao
 */
NovaExposicao.prototype.descricao = undefined;

