/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NovaNotificacao model module.
 * @module model/NovaNotificacao
 * @version 0.0.1
 */
export class NovaNotificacao {
  /**
   * Constructs a new <code>NovaNotificacao</code>.
   * @alias module:model/NovaNotificacao
   * @class
   * @param expoId {Number} 
   * @param artista {String} 
   */
  constructor(expoId, artista) {
    this.expoId = expoId;
    this.artista = artista;
  }

  /**
   * Constructs a <code>NovaNotificacao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NovaNotificacao} obj Optional instance to populate.
   * @return {module:model/NovaNotificacao} The populated <code>NovaNotificacao</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NovaNotificacao();
      if (data.hasOwnProperty('expoId'))
        obj.expoId = ApiClient.convertToType(data['expoId'], 'Number');
      if (data.hasOwnProperty('painelId'))
        obj.painelId = ApiClient.convertToType(data['painelId'], 'Number');
      if (data.hasOwnProperty('artista'))
        obj.artista = ApiClient.convertToType(data['artista'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} expoId
 */
NovaNotificacao.prototype.expoId = undefined;

/**
 * @member {Number} painelId
 */
NovaNotificacao.prototype.painelId = undefined;

/**
 * @member {String} artista
 */
NovaNotificacao.prototype.artista = undefined;

