/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NovoPainel model module.
 * @module model/NovoPainel
 * @version 0.0.1
 */
export class NovoPainel {
  /**
   * Constructs a new <code>NovoPainel</code>.
   * @alias module:model/NovoPainel
   * @class
   * @param autor {String} 
   */
  constructor(autor) {
    this.autor = autor;
  }

  /**
   * Constructs a <code>NovoPainel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NovoPainel} obj Optional instance to populate.
   * @return {module:model/NovoPainel} The populated <code>NovoPainel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NovoPainel();
      if (data.hasOwnProperty('autor'))
        obj.autor = ApiClient.convertToType(data['autor'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} autor
 */
NovoPainel.prototype.autor = undefined;

