/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Elemento} from './Elemento';

/**
 * The Painel model module.
 * @module model/Painel
 * @version 0.0.1
 */
export class Painel {
  /**
   * Constructs a new <code>Painel</code>.
   * @alias module:model/Painel
   * @class
   * @param nome {String} 
   * @param autor {String} 
   */
  constructor(nome, autor) {
    this.nome = nome;
    this.autor = autor;
  }

  /**
   * Constructs a <code>Painel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Painel} obj Optional instance to populate.
   * @return {module:model/Painel} The populated <code>Painel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Painel();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('autor'))
        obj.autor = ApiClient.convertToType(data['autor'], 'String');
      if (data.hasOwnProperty('elementos'))
        obj.elementos = ApiClient.convertToType(data['elementos'], [Elemento]);
    }
    return obj;
  }
}

/**
 * @member {String} nome
 */
Painel.prototype.nome = undefined;

/**
 * @member {String} autor
 */
Painel.prototype.autor = undefined;

/**
 * @member {Array.<module:model/Elemento>} elementos
 */
Painel.prototype.elementos = undefined;

