/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Perfil model module.
 * @module model/Perfil
 * @version 0.0.1
 */
export default class Perfil {
  /**
   * Constructs a new <code>Perfil</code>.
   * @alias module:model/Perfil
   * @class
   * @param id {Number} 
   * @param nome {String} 
   */
  constructor(id, nome) {
    this.id = id;
    this.nome = nome;
  }

  /**
   * Constructs a <code>Perfil</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Perfil} obj Optional instance to populate.
   * @return {module:model/Perfil} The populated <code>Perfil</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Perfil();
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Perfil.prototype.id = undefined;

/**
 * @member {String} nome
 */
Perfil.prototype.nome = undefined;

