/*
 * Swagger UnderExpo - OpenAPI 3.0
 * Definição OpenAPI 3.0 para a API do projeto UnderExpo.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Usuario model module.
 * @module model/Usuario
 * @version 0.0.1
 */
export default class Usuario {
  /**
   * Constructs a new <code>Usuario</code>.
   * @alias module:model/Usuario
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Usuario</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Usuario} obj Optional instance to populate.
   * @return {module:model/Usuario} The populated <code>Usuario</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Usuario();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Usuario.prototype.id = undefined;

/**
 * @member {String} nome
 */
Usuario.prototype.nome = undefined;

